### PR TITLE
Added height: auto utility class

### PR DESCRIPTION
**Pull request by Aneal07**
Please let me know if this is what you want. thanks.

### CODE REVIEW

**Comment by daniel-bergmann** [comment]
Hi @Aneal07, thanks for the contribution! Could you add it for the @media breakpoint for larger sizes as well?

**Comment by Aneal07** [comment]
Hi, I  added height: auto for large and extra large devices. please let me know if anything needs to change. thanks.

**Review by daniel-bergmann — CHANGES_REQUESTED** [review]
We only use one breakpoint in this framework. Please take a look at the sourcecode and see how we use big for desktop screen sizes, for example ".big\:h-10"

**Comment by Aneal07** [comment]
Could you check and let me know if is this what you want? thanks.

**Comment by daniel-bergmann** [comment]
Great job, I will merge it into the main branch

**Pull request merged**
